# Generated by Django 4.1.5 on 2023-03-23 03:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_servicebook_delete_vechilepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebook',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicebook',
            name='serviceDate',
            field=models.DateField(default=datetime.date(2023, 3, 23)),
        ),
        migrations.AlterField(
            model_name='servicebook',
            name='serviceTime',
            field=models.TimeField(default='09:00:59'),
        ),
    ]
