# Generated by Django 4.1.5 on 2023-03-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_servicebook_userid_alter_servicebook_servicedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebook',
            name='serviceTime',
            field=models.TimeField(default='22:04'),
        ),
    ]
